title: Track designer
hero_image: images/banner.png
description: Design you own interactive track for a ball to roll down.
meta_title: Track Designer
meta_description: Design you own interactive track for a ball to roll down.
keywords:
- unity
- ball
- marble
- 3d
- game
version: 1
listed: false
copyedit: false
last_tested: "2023-06-13"
steps:
  - title: You will make
  - title: Design the track
  - title: Add a ball
    completion:
      - engaged
  - title: Interactive objects
  - title: Track and goal effects
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: Share
  - title: What next?
    completion:
      - external
